package test;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import page.GoogleLoginPage;
import page.GoogleMailCreateNewEmail;
import page.GoogleMailSentEmailsPage;
import page.GoogleMailHomePage;

import java.util.concurrent.TimeUnit;

public class GoogleMailTest {

    private WebDriver driver;

    @BeforeMethod (alwaysRun = true)
    public void browserSetup() {
        driver = new ChromeDriver();
        driver.manage().deleteAllCookies();
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    }

    @Test(description = "Create a new mail, save it as a draft, and send to the recepient")
    public void googleMailTest() {

        String googleMailUrl = "https://mail.google.com/mail/u/0/#inbox";
        String emailSubject = "Message from Webdriver";


        new GoogleLoginPage(driver)
                .openPage()
                .enterEmailOrPhone("tyrmandyr1@gmail.com")
                .confirmEmailOrPhone()
                .enterPassword("@Tyrmandyr1!")
                .confirmPassword();
        new WebDriverWait(driver, 10).until(ExpectedConditions.urlMatches(googleMailUrl));

        Assert.assertSame(driver.getCurrentUrl(), googleMailUrl, "Login failed");

        new GoogleMailHomePage(driver).createNewEmail();

        new GoogleMailCreateNewEmail(driver)
                .enterEmailAddressee("al.hlebka@gmail.com")
                .enterEmailSubject(emailSubject)
                .enterEmailBody("Hello Aliaksei,\nthis message is generated by Webdriver.\nBest regards,\nAliaksei.");

        new GoogleMailCreateNewEmail(driver).sendEmail();

        new GoogleMailHomePage(driver).openSentEmailsPage();
        new WebDriverWait(driver,10).until(ExpectedConditions.urlMatches("https://mail.google.com/mail/u/0/#sent"));
        new GoogleMailSentEmailsPage(driver).openSentEmail(emailSubject);

        Assert.assertSame(driver
                        .findElement(By.xpath("//h2[@class='hP']"))
                        .getText(),
                emailSubject, "Email was not found in sent folder");
    }

    @AfterMethod(alwaysRun = true)
    public void closeBrowser() {
        driver.quit();
        driver = null;
    }
}