package test;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import page.GoogleLoginPage;
import page.GoogleMailCreateNewEmailPage;
import page.GoogleMailDraftsPage;
import page.GoogleMailEmailDetailsPage;
import page.GoogleMailHomePage;

public class GoogleMailSaveNewMailAsDraftAndDeleteTest {

    private WebDriver driver;

    @BeforeMethod(alwaysRun = true)
    public void browserSetup() {
        driver = new ChromeDriver();
        driver.manage().deleteAllCookies();
        driver.manage().window().maximize();
    }

    @Test(description = "Create new mail, save it as draft, and then delete it from Drafts folder")
    public void googleMailSaveMailAsDraftTest() {

        String login = "tyrmandyr1@gmail.com";
        String password = "@Tyrmandyr1!";
        String emailAddressee = "al.hlebka@gmail.com";
        String emailSubject = "Message from Webdriver";
        String emailBody = "Hello Aliaksei,\nthis message is generated by Webdriver.\nBest regards,\nAliaksei.";

        GoogleMailHomePage homePage = new GoogleLoginPage(driver).loginToGoogleMail(login, password);

        Assert.assertEquals(driver.getCurrentUrl(), homePage.getHomepageUrl(), "Login failed");

        GoogleMailCreateNewEmailPage createNewEmailPage = homePage.createNewEmail();
        createNewEmailPage.enterEmailAddressee(emailAddressee)
                .enterEmailSubject(emailSubject)
                .enterEmailBody(emailBody);
        homePage = createNewEmailPage.closeNewEmail();
        GoogleMailDraftsPage draftsPage = homePage.openDraftsPage();
        GoogleMailEmailDetailsPage emailDetailsPage = draftsPage.openDraftEmail(emailSubject);

        Assert.assertEquals(emailDetailsPage.getEmailAddresseeTextField().
                getText(), emailAddressee, "Email addressee is different from the expected one!");
        Assert.assertEquals(emailDetailsPage.getEmailBodyTextField()
                .getText(), emailBody, "Email body is different from the expected one!");

        draftsPage = emailDetailsPage.deleteDraftEmail();

        Assert.assertTrue(draftsPage.getNoDraftEmailsMessage().getText()
                        .contains("Нет сохраненных черновиков."), "Drafts folder is not empty!");

        homePage.logoutGoogleAccount();
    }

    @AfterMethod(alwaysRun = true)
    public void closeBrowser() {
        driver.quit();
        driver = null;
    }
}
