package test;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import page.GoogleLoginPage;
import page.GoogleMailHomePage;
import page.GoogleMailSentEmailsPage;

public class GoogleMailSendEmailTest {

    private WebDriver driver;

    @BeforeMethod (alwaysRun = true)
    public void browserSetup() {
        driver = new ChromeDriver();
        driver.manage().deleteAllCookies();
        driver.manage().window().maximize();
    }

    @Test(description = "Create a new mail, save it as a draft, and send to the recipient")
    public void googleMailSendEmailTest() {

        String googleMailUrl = "https://mail.google.com/mail/u/0/#inbox";
        String login = "tyrmandyr1@gmail.com";
        String password = "@Tyrmandyr1!";
        String emailAddressee = "al.hlebka@gmail.com";
        String emailSubject = "Message from Webdriver";
        String emailBody = "Hello Aliaksei,\nthis message is generated by Webdriver.\nBest regards,\nAliaksei.";

        new GoogleLoginPage(driver).loginToGoogleMail(login, password);
        new WebDriverWait(driver, 10).until(ExpectedConditions.urlMatches(googleMailUrl));

        Assert.assertSame(driver.getCurrentUrl(), googleMailUrl, "Login failed");

        GoogleMailHomePage homePage = new GoogleMailHomePage(driver);
        GoogleMailSentEmailsPage sentEmailsPage = new GoogleMailSentEmailsPage(driver);

        homePage.createNewEmail()
                .enterEmailAddressee(emailAddressee)
                .enterEmailSubject(emailSubject)
                .enterEmailBody(emailBody)
                .sendEmail()
                .openSentEmailsPage()
                .openSentEmail(emailSubject);

        Assert.assertSame(sentEmailsPage.getSentEmailSubject()
                .getText(), emailSubject, "Email subject is different from the expected one!");
        Assert.assertSame(sentEmailsPage.getSentEmailBody()
                .getText(), emailBody, "Email body is different from the expected one!");

        homePage.quitGoogleAccount();
    }

    @AfterMethod(alwaysRun = true)
    public void closeBrowser() {
        driver.quit();
        driver = null;
    }
}