package test;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import page.*;

import java.util.concurrent.TimeUnit;

public class GoogleMailSendEmailTest {

    private WebDriver driver;

    @BeforeMethod (alwaysRun = true)
    public void browserSetup() {
        driver = new ChromeDriver();
        driver.manage().deleteAllCookies();
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    }

    @Test(description = "Create a new mail, save it as a draft, and send to the recipient")
    public void googleMailSendEmailTest() {

        final String GOOGLE_MAIL_URL = "https://mail.google.com/mail/u/0/#inbox";
        String login = "tyrmandyr1@gmail.com";
        String password = "@Tyrmandyr1!";
        String emailAddressee = "al.hlebka@gmail.com";
        String emailSubject = "Message from Webdriver";
        String emailBody = "Hello Aliaksei,\nthis message is generated by Webdriver.\nBest regards,\nAliaksei.";

        new GoogleLoginPage(driver).loginToGoogleMail(login, password);
        new WebDriverWait(driver, 10).until(ExpectedConditions.urlMatches(GOOGLE_MAIL_URL));

        Assert.assertSame(driver.getCurrentUrl(), GOOGLE_MAIL_URL, "Login failed");

        GoogleMailHomePage homePage = new GoogleMailHomePage(driver);
        GoogleMailCreateNewEmail createNewEmail = new GoogleMailCreateNewEmail(driver);
        GoogleMailSentEmailsPage sentEmailsPage = new GoogleMailSentEmailsPage(driver);
        homePage.createNewEmail();

        createNewEmail
                .enterEmailAddressee(emailAddressee)
                .enterEmailSubject(emailSubject)
                .enterEmailBody(emailBody);

        createNewEmail.sendEmail();
        homePage.openSentEmailsPage();
        sentEmailsPage.openSentEmail(emailSubject);

        Assert.assertSame(sentEmailsPage.getSentEmailSubject()
                .getText(), emailSubject, "Email subject is different from the expected one!");
        Assert.assertSame(sentEmailsPage.getSentEmailBody()
                .getText(), emailBody, "Email body is different from the expected one!");

        homePage.quitGoogleAccount();
    }

    @AfterMethod(alwaysRun = true)
    public void closeBrowser() {
        driver.quit();
        driver = null;
    }
}