package test;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import page.GoogleLoginPage;
import page.GoogleMailCreateNewEmail;
import page.GoogleMailDraftsPage;
import page.GoogleMailHomePage;

import java.util.concurrent.TimeUnit;

public class GoogleMailSaveNewMailAsDraftAndDeleteTest {

    private WebDriver driver;

    @BeforeMethod(alwaysRun = true)
    public void browserSetup() {
        driver = new ChromeDriver();
        driver.manage().deleteAllCookies();
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    }

    @Test(description = "Create new mail and save it as draft")
    public void googleMailSaveMailAsDraftTest() {

        String googleMailUrl = "https://mail.google.com/mail/u/0/#inbox";
        String googleMailDraftsFolderUrl = "https://mail.google.com/mail/u/0/#drafts";
        String emailAddressee = "al.hlebka@gmail.com";

        new GoogleLoginPage(driver)
                .openPage()
                .enterEmailOrPhone("tyrmandyr1@gmail.com")
                .confirmEmailOrPhone()
                .enterPassword("@Tyrmandyr1!")
                .confirmPassword();
        new WebDriverWait(driver, 10).until(ExpectedConditions.urlMatches(googleMailUrl));

        Assert.assertSame(driver.getCurrentUrl(), googleMailUrl, "Login failed");

        new GoogleMailHomePage(driver).createNewEmail();

        new GoogleMailCreateNewEmail(driver)
                .enterEmailAddressee(emailAddressee)
                .enterEmailSubject("Message from Webdriver")
                .enterEmailBody("Hello Aliaksei,\nthis message is generated by Webdriver.\nBest regards,\nAliaksei.")
                .closeNewEmail();

        new GoogleMailHomePage(driver).openDraftsPage();
        new WebDriverWait(driver, 10).until(ExpectedConditions.urlMatches(googleMailDraftsFolderUrl));

        new GoogleMailDraftsPage(driver)
                .selectAllDraftEmails()
                .deleteAllDraftEmails();

        Assert.assertTrue(driver.findElement(By.xpath("//td[@class='TC']")).getText().contains("Нет сохраненных черновиков."),
                "Drafts folder is not empty!");

        new GoogleMailHomePage(driver).quitGoogleAccount();
    }

    @AfterMethod(alwaysRun = true)
    public void closeBrowser() {
        driver.quit();
        driver = null;
    }
}
